# Generated by Django 3.1.5 on 2021-01-25 12:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('novice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novicapage',
            name='preview_text',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='novicapage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
