# Generated by Django 3.1.8 on 2021-07-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novice', '0002_auto_20210125_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novicapage',
            options={'verbose_name': 'Newspage'},
        ),
    ]
