# Generated by Django 3.1.5 on 2021-01-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contact_showsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='showSnippet',
            field=models.BooleanField(default=False),
        ),
    ]
