# Generated by Django 3.1.8 on 2021-07-08 06:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0012_newsletter_showsnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_links', wagtail.core.fields.StreamField([('page_link', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='If empty, subpage title will be used', label='Name', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Subpage'))])), ('external_link', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Name')), ('url', wagtail.core.blocks.URLBlock(label='URL'))]))], verbose_name='Header links')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
