# Generated by Django 3.1.8 on 2021-07-08 13:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_metasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StreamBlock([('color_section', wagtail.core.blocks.StructBlock([('color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'Bela'), ('blue', 'Modra'), ('yellow', 'Rumena'), ('pink', 'Roza')], label='Barva')), ('body', wagtail.core.blocks.StreamBlock([('headline', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Naslov')), ('description', wagtail.core.blocks.RichTextBlock(label='Opis', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Slika', required=False))], icon='title', label='Naslov', template='home/blocks/headline.html')), ('rich_text', wagtail.core.blocks.StructBlock([('position', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Leva'), ('center', 'Sredinska'), ('right', 'Desna')], label='Poravnava')), ('aligned_text', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock(label='Besedilo'))], label='Obogateno besedilo'))], icon='pilcrow', label='Obogateno besedilo', template='home/blocks/rich_text.html')), ('double_cards', wagtail.core.blocks.StructBlock([('text1', wagtail.core.blocks.CharBlock(label='Besedilo 1')), ('image1', wagtail.images.blocks.ImageChooserBlock(label='Ikona 1')), ('text2', wagtail.core.blocks.CharBlock(label='Besedilo 2')), ('image2', wagtail.images.blocks.ImageChooserBlock(label='Ikona 2'))], icon='title', label='Dve kartici', template='home/blocks/double_cards.html')), ('triple_cards', wagtail.core.blocks.StructBlock([('title_big1', wagtail.core.blocks.CharBlock(label='Naslov - velik 1', required=False)), ('title_small1', wagtail.core.blocks.CharBlock(label='Naslov - mali 1', required=False)), ('description1', wagtail.core.blocks.CharBlock(label='Opis 1', required=False)), ('image1', wagtail.images.blocks.ImageChooserBlock(label='Ikona 1')), ('title_big2', wagtail.core.blocks.CharBlock(label='Naslov - velik 2', required=False)), ('title_small2', wagtail.core.blocks.CharBlock(label='Naslov - mali 2', required=False)), ('description2', wagtail.core.blocks.CharBlock(label='Opis 2', required=False)), ('image2', wagtail.images.blocks.ImageChooserBlock(label='Ikona 2')), ('title_big3', wagtail.core.blocks.CharBlock(label='Naslov - velik 3', required=False)), ('title_small3', wagtail.core.blocks.CharBlock(label='Naslov - mali 3', required=False)), ('description3', wagtail.core.blocks.CharBlock(label='Opis 3', required=False)), ('image3', wagtail.images.blocks.ImageChooserBlock(label='Ikona 3'))], icon='title', label='Tri kartice', template='home/blocks/triple_cards.html'))]))]))]))], default='', verbose_name='Content'),
        ),
    ]
