# Generated by Django 3.2.21 on 2023-09-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20230914_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metasettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='ogsettings',
            name='site',
        ),
    ]
