# Generated by Django 3.2.21 on 2023-09-15 10:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20230914_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('name_es', models.CharField(blank=True, default='', max_length=255, verbose_name='Spanish')),
                ('name_it', models.CharField(blank=True, default='', max_length=255, verbose_name='Italian')),
                ('name_sl', models.CharField(blank=True, default='', max_length=255, verbose_name='Slovenian')),
                ('name_lt', models.CharField(blank=True, default='', max_length=255, verbose_name='Lithuanian')),
                ('name_fi', models.CharField(blank=True, default='', max_length=255, verbose_name='Finnish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', wagtail.fields.RichTextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.language')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('body', wagtail.fields.RichTextField(blank=True, null=True)),
                ('exercise', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='home.exercise')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
