# Generated by Django 3.2.21 on 2023-09-19 09:20

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_answer_exercise_language_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='English'),
        ),
    ]
